CREATE TABLE IF NOT EXISTS coins(
    coin_id TEXT PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    symbol TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    purchase_price_average DOUBLE PRECISION NOT NULL,
    total_cost DOUBLE PRECISION NOT NULL,
    pnl DOUBLE PRECISION NOT NULL,
    version INTEGER NOT NULL DEFAULT 1
);
